repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: no-commit-to-branch
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.4
    hooks:
      - id: ruff-format
        args: [ --preview ]
      - id: ruff
        args: [ --preview, --fix]

  - repo: https://github.com/python-poetry/poetry
    rev: '1.8.4'  # add version here
    hooks:
      - id: poetry-check
