name: Code Quality

on:
  pull_request:
  workflow_dispatch:
jobs:
  lint:
    name: Code Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - run: uv python install 3.11
      - run: make
      - run: make check
      - run: make mypy
