name: Publish docs GH Pages
on:
  pull_request: # todo: remove this after testing
  release:
    types: [ published ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:

  create-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - run: uv python install 3.11

      - run: make install-docs
      - run: make doc

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
          keep_files: true
